#pragma once
#include <string>
const std::string STATE_MESSAGE = "STATE_MESSAGE";
enum  MESSAGE_TYPE
{
	BOUNDINGSPHERE = 0,
	CLIENT_LOGIN = 1,
	VIEWMATRIX = 2,
	PROJECTIONMATRIX = 3,
	RESIZE = 4,
	CLIENT_INITIALIZED = 5,
	REQUESTED_FRAME_STAMP = 5,
	RECEIVED_FRAME_STAMP = 6
};